-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.rating
(
    id_rating varchar(100) NOT NULL,
    user_id varchar(100),         -- Usuario que califica
    id_anuncio varchar(100) NOT NULL,  -- Anuncio que se califica
    rating integer,           -- La calificación dada
    score_assigned integer,   -- El puntaje asignado al usuario calificado
    rated_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT rating_pkey PRIMARY KEY (id_rating)
);

CREATE TABLE IF NOT EXISTS public.rating_auditoria
(
    id_rau serial NOT NULL,
    rating_id varchar(100) NOT NULL,  -- ID de la calificación que se audita
    anuncio_id varchar(100),
    user_id varchar(100),
    cambio character varying(500) COLLATE pg_catalog."default",
    fecha_cambio timestamp with time zone NOT NULL,
    CONSTRAINT rating_auditoria_pkey PRIMARY KEY (id_rau)
);

ALTER TABLE IF EXISTS public.rating_auditoria
    ADD CONSTRAINT rating_auditoria_rating_id_fkey FOREIGN KEY (rating_id)
    REFERENCES public.rating (id_rating) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
